[build]
builder = "nixpacks"

[build.nixpacks]
packages = ["dotnet-sdk_8"]

buildCommand = "dotnet restore && dotnet publish Menro.Web/Menro.Web.csproj -c Release -o out"

[deploy]
startCommand = "dotnet out/Menro.Web.dll"
